### https://blog.tkav.dev/running-your-lamp-stack-on-docker-containers ###
version: '3.9'

### SERVICES #################
services:
  ### PHP ####################
  php:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2.3}
        - PHP_VARIANT=${PHP_VARIANT:-fpm-alpine}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS:-mysqli pdo pdo_mysql}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/websites:/var/www/html
    environment:
      - TZ=${TZ:-America/New_York}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - DB_USER=${DB_USER:-admin}
      - DB-PASSWORD=${DB_PASSWORD:-change-me}
    container_name: ${DOCKER_PREFIX:-dev-}php
    restart: unless-stopped
  ### CADDY ##################
  caddy:
    build:
      context: ./docker/caddy
      args:
        - CADDY_VERSION=${CADDY_VERSION:-2.6.4}
        - CADDY_MODULES=${CADDY_MODULES}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "${CADDY_PORT:-80}:80"
      - "${CADDY_SECURE_PORT:-443}:443"
    volumes:
      - ${PROJECT_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PROJECT_ROOT}/websites:/var/www/html
      - caddy-config:/config
      - caddy-data:/data
    environment:
      - TZ=${TZ:-America/New_York}
      - CF_API_TOKEN=${CF_API_TOKEN}
    container_name: ${DOCKER_PREFIX:-dev-}caddy
    restart: unless-stopped
  ### MARIADB ################
  db:
    image: mariadb:${DB_VERSION:-10.11.2}
    networks:
      - backend
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/config
    environment:
      - TZ=${TZ:-America/New_York}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root-change-me}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-change-me}
    container_name: ${DOCKER_PREFIX:-dev-}db
    restart: unless-stopped
networks:
  frontend:
    name: ${DOCKER_PREFIX:-dev-}frontend
  backend:
    name: ${DOCKER_PREFIX:-dev-}backend
volumes:
  caddy-config:
  caddy-data:
  db-data:
