version: '3.3'
services:
  caddy:
    container_name: caddy
    build:
        context: ./docker/caddy
        args:
            - CADDY_VERSION=$CADDY_VERSION
            - CADDY_MODULES=$CADDY_MODULES
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /home/websites:/usr/share/caddy
      - caddy_data:/data
      - caddy_config:/config
#    depends_on:
#      - php-fpm
#  php-fpm:
#    container_name: php-fpm
#    build: ./docker/php
#    restart: unless-stopped
#    volumes:
#      - /home/websites:/usr/share/caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    external:
      name: main
